name_path: prometheus
name_title:
- Prometheus®
name_description: Prometheus
references:
- type: Upstream website
  name: prometheus.io
  href: https://prometheus.io/
- type: Upstream repository
  name: prometheus/prometheus
  href: https://github.com/prometheus/prometheus
attributions:
- trademark: Prometheus
  owner: The Linux Foundation
